name: PAPERLIGHTSMUSIC
favicon: null
layout_spectrum: 0.89403
typography_spectrum: 1
title: PAPER LIGHTS MUSIC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030102'
    - '#fdfefe'
    - '#8d8475'
    - '#3f1a00'
    - '#685b36'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
